### ISSUE TITLE
More explicit wallet options

### ISSUE THREAD

**Issue by HypeDis** [Stakely/lto-network-ledger-wallet-ui#1]
I just accidentally transferred a big chunk of my LTO instead of leasing it, and while I recognize that ultimately it is my fault  it is far too easy to make this mistake with the current UI. 
My suggestions would be:
Quick fix:
Have the select be empty by default
Better Fix:
Have all of the options visible as a button group

**Comment by iicc1** [comment]
Thanks for your comment. That's something that we hadn't thought about.

An alternative solution might be to add the transaction type to the sign transaction button.
Instead of displaying "Sign Transaction", show: "Sign Transfer", "Sign Start Lease", and so on.

In this way, the user double-checks the transaction type before signing with the Ledger device.

**Comment by iicc1** [comment]
The web app now displays the transaction type on the sign transaction button.
If you think this is not enough, feel free to reopen this issue.
